
export const ADD_NEW_BOOK = "ADD_NEW_BOOK";
export const FETCH_BOOKS = "FETCH_BOOKS";
export const SORT_BOOK = "SORT_BOOK";
export const SORT_BORROW = "SORT_BORROW";
export const REMOVE_SELECTED_BOOK = "REMOVE_SELECTED_BOOK";
export const ADD_RETURN_BOOK = "ADD_RETURN_BOOK";
export const REMOVE_SELECTED_BORROW = "REMOVE_SELECTED_BORROW"
export const ADD_BORROW = "ADD_BORROW"
export const SELECTED_BOOK_INDEX = "SELECTED_BOOK_INDEX";
export const SELECTED_BORROW_INDEX = "SELECTED_BORROW_INDEX";
export const TOGGLE_BORROW_DIALOG = "TOGGLE_BORROW_DIALOG";
export const TOGGLE_RETURN_DIALOG = "TOGGLE_RETURN_DIALOG";
export const REMOVE_DIALOG = "REMOVE_DIALOG";
export const CLOSE_BORROW_DIALOG = "CLOSE_BORROW_DIALOG"
export const CLOSE_RETURN_DIALOG = "CLOSE_RETURN_DIALOG"
